### ISSUE TITLE
Searching for places alongside locations

### ISSUE THREAD

**Issue by divanvb** [guillefd/gmapsAutocomplete-RC1#2]
How would I go about implementing places along side google maps, I see you do include the library places but when search for a restaurant for example, the autocomplete doesn't bring it up up using normal google maps, it does.

Do you mind helping add the places as well in the search?

**Comment by guillefd** [comment]
Sure, the API offers 4 types of prediction request, [see docs](https://developers.google.com/maps/documentation/javascript/3.exp/reference#AutocompletionRequest):    
- geocode (current type used), establishment (businesses), regions and cities.  

I guess you may need to set "establishment" as the type of prediction requested, this will retrieve businesses names instead of addresses.  
In this app example, just change where it says "geocode" and  set "establishment".  

**src/pages/modal-autocomplete-items.ts, line 44:**  [see commit](https://github.com/guillefd/ionic2-google-maps-autocomplete/commit/3535620509fc170d340fada89959c156ed7ebd93)
```
        ....
        let config = { 
            types:  ['geocode'], // other types available in the API: 'establishment', 'regions', and 'cities'
            input: this.autocomplete.query, 
            componentRestrictions: { country: 'AR' } 
        }
        this.acService.getPlacePredictions(config, function (predictions, status) {
        ...
```
